# -----------------------------
# Site basics
# -----------------------------
title: "sbinhigher · Portfolio"
description: "Seongbin Ko — Data Analyst"
url: "https://sbinhigher.github.io"
baseurl: ""          # user/organization site -> keep empty
locale: "ko"

# -----------------------------
# Remote theme (WORKING)
# -----------------------------
# The previous remote_theme (startbootstrap/startbootstrap-agency-jekyll) 404'd.
# This one is actively maintained and supports GitHub Pages.
remote_theme: raviriley/agency-jekyll-theme

# -----------------------------
# Plugins (GitHub Pages compatible)
# -----------------------------
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# -----------------------------
# Markdown & syntax
# -----------------------------
markdown: kramdown
highlighter: rouge

# -----------------------------
# Permalinks
# -----------------------------
permalink: pretty

# -----------------------------
# Defaults (optional, safe)
# -----------------------------
defaults:
  - scope:
      path: ""
    values:
      layout: default

# -----------------------------
# Excludes (optional)
# -----------------------------
exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

# -----------------------------
# Notes
# -----------------------------
# This theme reads section content from _data/sitetext.yml by default.
# We customized about.html to prefer _data/sitetext_overrides.yml when present.
# Keep both files if desired; overrides take precedence for the About section.